// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ08ClNyRtAA087PD_GfdUKRbO9_pJ7Sg',
    appId: '1:1086367037818:web:35d4354b1d2a2d064dbec3',
    messagingSenderId: '1086367037818',
    projectId: 'estacao-livre',
    authDomain: 'estacao-livre.firebaseapp.com',
    databaseURL: 'https://estacao-livre-default-rtdb.firebaseio.com',
    storageBucket: 'estacao-livre.appspot.com',
    measurementId: 'G-0JB2ZEW1HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoJFq4Cmiwm9OOq8rWUWWJ2q6riSLIdqc',
    appId: '1:1086367037818:android:9670f7560104018c4dbec3',
    messagingSenderId: '1086367037818',
    projectId: 'estacao-livre',
    databaseURL: 'https://estacao-livre-default-rtdb.firebaseio.com',
    storageBucket: 'estacao-livre.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAusiMu-pDRE0xBa_8wXVH29WO6w5KfSqQ',
    appId: '1:1086367037818:ios:dc04760b67c1348f4dbec3',
    messagingSenderId: '1086367037818',
    projectId: 'estacao-livre',
    databaseURL: 'https://estacao-livre-default-rtdb.firebaseio.com',
    storageBucket: 'estacao-livre.appspot.com',
    iosClientId: '1086367037818-kv2h410bbsh1e068td2bm3h9fmov1c3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bus',
  );
}
